# Generated by Django 3.2.5 on 2021-07-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_directories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('flight_id', models.TextField(verbose_name='Идентификатор полета')),
                ('booking_token', models.TextField(verbose_name='Токен брони')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена')),
                ('flight_date', models.DateField(verbose_name='Дата вылета')),
                ('airlines', models.CharField(max_length=100, verbose_name='Авиакомпании')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность полета')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='core.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='core.city')),
            ],
            options={
                'verbose_name': 'Полет',
                'verbose_name_plural': 'Полеты',
            },
        ),
    ]
